apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-storage-claim
  labels:
    app: nextcloud
spec:
  storageClassName: nextcloud-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 80Gi