apiVersion: v1
kind: PersistentVolume
metadata:
  name: nextcloud
  labels:
    type: local
    app: nextcloud
spec:
  storageClassName: nextcloud-storage
#  persistentVolumeReclaimPolicy: Delete - deletes all storage if claim is removed
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
              - 10.0.0.16
            # topologyKey: kubernetes.io/hostname - load balancing if multiple nodes with same value, not possible in this case
  local:
    path: "/mnt/kubestorage/nextcloud"